### ISSUE TITLE
some of devDependencies are in Dependencies

### ISSUE THREAD

**Issue by mhmdtshref** [fack2/Football_teams#32]
https://github.com/fack2/Football_teams/blob/b493e53a294ea9df3b5bdd11605b3a5021420fab/package.json#L28-L34

Some of the devDependencies  are in dependencies. You don't need these modules in the production-mode:
```json
{
    "eslint": "^6.1.0",
    "supertest": "^4.0.2"
}
```

**Comment by SajaLahaleeh** [comment]
we did it @mhmdtshref
